#! /bin/bash

# This script attempts to run the entire simulation. If a component of the simulation
# fails, it halts execution and informs the user which component has failed. 
# The script is intended to be executed in the direcoty that will store all of the 
# files generated by the simulation as well as the templates, filters, input catalog, and 
# simulation.params files.

if [ ! -e "simulation.params" ]; then
  echo "The current directory does not contain a configuration file (simulation.params)."
  exit 1
fi

source ./simulation.params

# copy input files into local directory
cp $RootDirectory/input/* .
cp -r $RootDirectory/filters/ .
cp -r $RootDirectory/templates/ .

mv $InputModels $InputModels.raw

filter_by_column.py --column 4 --limit 24.5 < $InputModels.raw > $InputModels

Commands=(MakeSimulatedPhotometry.sh \
          MakeModelGrid.sh \
          RunPhoto-z.sh )

for cmd in ${Commands[@]}; do

    $cmd

    if [[ $? != 0 ]]; then

        errlog "$(date): It looks like $script did not finish successfully."
    fi
done

errlog "Finished simulation at $(date)"
